### ISSUE TITLE
TypeError: f.current is null - using useState in the remote app

### ISSUE THREAD

**Issue by elpddev** [gioboa/react-microfrontend-demo#1]
Hi, thank you for a great work!

I'm trying to setup the same project and add `useState` to the main component.  Without it, it works great with bare jsx components.

When adding 'useState` to the remote app, it then fails with the error:

```
TypeError: f.current is null
    useState React
    ke App.tsx:4
    Ri bootstrap.f85ccc46.js:30
```

```js
import {useState} from 'react';

export default () => {
	const [a, setA] = useState(2);
	return (<div>...</div>);
};
```

Not sure why the react production build fails inside it on `useState` activation.

**Comment by gioboa** [comment]
Thanks for the feedback @elpddev 
I will look at this issue and I will let you know 😉

**Comment by gioboa** [comment]
I managed useState + useEffect in the example 👍

**Comment by elpddev** [comment]
Thank you! I can confirm its working on my setup.
