### ISSUE TITLE
Support for runtime microfrontends

### ISSUE THREAD

**Issue by gigincg** [gioboa/react-microfrontend-demo#8]
Is it possible to load the MFE at runtime, based on the URL the MFE is built and published at, instead of hardcoding the MFE configuration and imports in the Host itself?

cc: @gioboa

**Comment by gioboa** [comment]
Hi @gigincg 
yes, you can, [here ](https://github.com/module-federation/vite/blob/aaa23f59a8fbc7fc054010ba453bdc20186f9ac0/examples/vite-webpack-rspack/host/src/App.tsx#L28) is an example.
